Feature/#181 Selector 구현
BDD-CLUB/01-doo-re-front pull request #183
Opened 2024-03-28 11:33 UTC by yeonddori

### 관련 이슈

- close #181

### 작업 요약

-  Chakra UI의 Menu를 활용하여 Selector 컴포넌트를 구현하였습니다.

### 작업 상세 설명

- 처음엔 Selector의 필드 디자인을 변경하는 것으로 시작하였으나, option은 따로 커스터마이징이 불가능하여 비슷한 Menu 컴포넌트를 활용해 제작하였습니다.
- MenuList은 `position: absolute`을 자체적으로 가지고 있어 `w="100%"(minW 포함)`이 적용이 되지 않기에 훅을 이용하여 너비를 가져와 적용하는 걸로 대체했습니다. `position: relative`도 적용이 안 돼서 이 방법 말고도 좋은 방법이 있다면 알려주시면 감사하겠습니다!

### 리뷰 요구 사항

- 피그마에서는 textStyle이 `bold_xl`로 되어있지만, 제가 보기에 너무 크다는 느낌이 들어서 일단 `bold_md`로 해놓긴 했습니다. 피그마대로 바꾸는 게 나을지 아니면 지금 상태가 나은지 의견을 여쭙고 싶습니다!
- 또한, 옵션을 선택할 때 첫 번째 옵션과 마지막 옵션에 마우스를 호버하면 현재는 MenuList와 MenuItem 사이에 틈이 있습니다. 이는 `p=0`으로 두면 틈을 없앨 수 있긴 한데 어떤 것이 좋을지 이것도 의견을 여쭙고 싶습니다!
- 저는 딘님과 다르게 리스트를 넣도록 하였는데... 수정하는 게 좋을까요?😅
```tsx
import { Box } from '@chakra-ui/react';

import Selector from '@/components/Selector';

const Page = () => {
  return (
    <Box w="300px" m="20">
      <Selector placeholder="작물을 선택해주세요" label={['토마토', '고구마', '당근', '완두콩', '벼']} />
    </Box>
  );
};

export default Page;
```
- 리뷰 예상 시간 : 7분

### 미리 보기
#### bold_xl
![스크린샷 2024-03-28 195328](https://github.com/BDD-CLUB/01-doo-re-front/assets/126975394/810ef9ef-b33a-4072-8cf4-764c5c261465)
#### bold_md
![스크린샷 2024-03-28 195208](https://github.com/BDD-CLUB/01-doo-re-front/assets/126975394/9e34d661-e460-4d21-87fb-a970dde81dce)

#### `p=0`이 아닐 때 (bold_md)
![스크린샷 2024-03-28 200204](https://github.com/BDD-CLUB/01-doo-re-front/assets/126975394/b416610c-fa31-4016-97c0-c081c6c87b3b)
#### `p=0`일 때 (bold_md)
![스크린샷 2024-03-28 200212](https://github.com/BDD-CLUB/01-doo-re-front/assets/126975394/d821d3a7-07aa-46c8-bb75-283b6c2e7930)

2024-03-31 12:32 UTC, llddang requested changes
> 피그마에서는 textStyle이 bold_xl로 되어있지만, 제가 보기에 너무 크다는 느낌이 들어서 일단 bold_md로 해놓긴 했습니다. 피그마대로 바꾸는 게 나을지 아니면 지금 상태가 나은지 의견을 여쭙고 싶습니다!

저도 bold_md가 제목이랑 차이가 나면서 좋은 것 같습니다.

> 옵션을 선택할 때 첫 번째 옵션과 마지막 옵션에 마우스를 호버하면 현재는 MenuList와 MenuItem 사이에 틈이 있습니다. 이는 p=0으로 두면 틈을 없앨 수 있긴 한데 어떤 것이 좋을지 이것도 의견을 여쭙고 싶습니다!

저도 p=0일 경우 딱 여백이 없어서 약간 답답하나, figma에서도 p=0 입니다.
그래서 이 부분은 padding을 0으로 주는 것이 좋을 것 같습니다.

> 저는 딘님과 다르게 리스트를 넣도록 하였는데... 수정하는 게 좋을까요?😅

selector 어떻게 사용되는지에 따라서 다를 것 같은데요. 
일단 저희는 selector를 string을 선택할 때만 사용하므로 지금 이대로 괜찮을 것 같습니다!

2024-03-31 12:32 UTC, llddang commented on src/components/Selector/index.tsx
> +        rightIcon={<BiChevronDown />}
현재 아이콘이 너무 작게 보입니다.
`fontSize` props로 아이콘의 크기를 조절가능합니다.
수정해주시면 좋을 것 같습니다.

2024-03-31 12:32 UTC, llddang commented on src/components/Selector/types.ts
> +}
이렇게 props를 설정할 경우, selected된 요소를 알 수 가 없습니다.
그래서 선택된 MenuItem의 content를 state로 저장할 수 있어야 할 것 같습니다.

```tsx
export interface SelectorProps {
  selected: string | undefined;
  label: string[];
  handleSelector: (data: string) => void;
}
```
`placeholder`역할을 `selected`가 대신하구요. 
handleSelector 함수를 이용해 선택된 아이템의 상태를 저장할 수 있도록 합니다.

사용방법은 Selector 컴포넌트의 MenuItem에 click이벤트로 handleSelector를 넘겨주면 됩니다.
```tsx
<MenuItem onClick={() => handleSelector(item)} > {item}
```
위의 내용은 props와 element(요소)들을 생략해서 간단하게 보였습니다.

이제 그럼 Selector 컴포넌트를 불러올 때 아래와 같은 방식으로 불러올 수 있습니다.

```tsx
'use client';

import { Box } from '@chakra-ui/react';
import { useState } from 'react';

import Selector from '@/components/Selector';

const Page = () => {
  const [crop, setCrop] = useState<string | undefined>();

  return (
    <Box w="300px" m="20">
      <Selector selected={crop} label={['토마토', '고구마', '당근', '완두콩', '벼']} handleSelector={setCrop} />
    </Box>
  );
};

export default Page;
```

지금의 방식으로는 state를 저장할 수 없어서 변경해주시면 좋을 것 같습니다.

2024-03-31 14:51 UTC, yeonddori commented on src/components/Selector/types.ts
> +}
아 제가 선택된 걸 보이도록 안했네요! 감사합니다!

`selected: string | undefined;`
`const [crop, setCrop] = useState<string | undefined>();`
혹시 이 두 코드에서 undefined를 붙여야 하는 이유는 무엇일까요??

```tsx
export interface SelectorProps {
  selected: string;
  label: string[];
  handleSelector: (data: string) => void;
}
```
```tsx
'use client';

import { Box } from '@chakra-ui/react';
import { useState } from 'react';

import Selector from '@/components/Selector';

const Page = () => {
  const [crop, setCrop] = useState<string>('작물을 선택해주세요');

  return (
    <Box w="300px" m="20">
      <Selector selected={crop} label={['토마토', '고구마', '당근', '완두콩', '벼']} handleSelector={setCrop} />
    </Box>
  );
};

export default Page;
```
이렇게 해도 되는 것 같아서 undefined를 붙이는 이유가 궁금합니다..!

2024-03-31 14:55 UTC, yeonddori commented on src/components/Selector/types.ts
> +}
아, useState 초기값에 빈 괄호를 쓸 수 있어서 그렇군요!

2024-04-01 06:20 UTC, jasper200207 approved these changes
👍
코멘트는 있는데 별로 중요한 내용은 아닙니다

2024-04-01 06:20 UTC, jasper200207 commented on src/components/Selector/types.ts
> +  selected: string | undefined;
이것도 큰 상관은 없는데
`selected?: string;`도 같은 역할인 걸로 알고 있습니다.

2024-04-01 06:20 UTC, jasper200207 commented on src/components/Selector/index.tsx
> +  }, []);
큰 상관은 없을 듯 하긴 한데
menuRef.current 가 null 이거나 바뀔때를 고려해서
```typescript
useEffect(() => {
  if (menuRef.current) {
    setMenuWidth(`${menuRef.current.offsetWidth}px`);
  }
}, [meunRef.current]);
```
로 바꾸는 것도 좋을 듯 합니다.

2024-04-01 13:14 UTC, llddang requested changes

2024-04-01 13:14 UTC, llddang commented on src/components/Selector/index.tsx
> +        <Text textStyle="bold_md">{selected}</Text>
지금 `selected`의 값이 `undefined`도 가능한데요.
이렇게 되면 처음에 빈 값이 들어갈 가능성이 보입니다.
여기서 한번 `selected`가 `undefined`인지 확인을 하는 코드가 있거나,
`selected type`에 `undefinded`를 빼야할 것 같습니다.

2024-04-01 13:14 UTC, llddang commented on src/components/Selector/types.ts
> +  selected: string | undefined;
음 딘님의 말씀대로 위와 같이 작성할 수 있는데요. 이렇게 되면 components에 selected 속성을 넣지 않아도 에러가 뜨지 않습니다.
이렇게 되면 실수로 selected를 빼뜨렸을 때, selector에 선택된 값으로 계속 빈 값이 뜨게 될 수도 있을 것 같습니다.
그래서 저는 selected라는 props가 컴포넌트에 무조건 들어가야한 다는 생각으로 `selected: string | undefined`와 같이 추천해드렸습니다~!

2024-04-03 16:26 UTC, yeonddori commented on src/components/Selector/index.tsx
> +  }, []);
이렇게 쓰면 eslint에 걸려 의존성 배열을 지우고 빈 괄호로 두길 권장하는데, 일단 빈 괄호 그대로 둬도 괜찮을까요?  `menuRef.current`와 같이 mutable 값은 컴포넌트를 다시 렌더링하지 않기 때문에 의존성으로 두면 안된다고, 불필요한 의존성으로 간주된다고 합니다..!

2024-04-03 16:42 UTC, yeonddori commented on src/components/Selector/index.tsx
> +        <Text textStyle="bold_md">{selected}</Text>
저는 `selected`의 초기값이 `undefined`도 없이 항상 존재해야 한다고 생각해서 그냥 빼버렸습니다..!

2024-04-04 06:09 UTC, jasper200207 commented on src/components/Selector/index.tsx
> +  }, []);
엇.... 그 관점에서 보면 빈괄호가 맞는 듯 하네요.... 빈괄호도 괜찮을 듯 합니다!

2024-04-04 06:10 UTC, jasper200207 approved these changes
👍

2024-04-04 10:11 UTC, llddang approved these changes
수고하셨습니다!

2024-04-04 10:11 UTC, merged