Feature/#205 DatePicker 구현
BDD-CLUB/01-doo-re-front pull request #209
Opened 2024-04-11 12:53 UTC by yeonddori

### 관련 이슈

- close #205

### 작업 요약

- 스터디 생성 모달에 쓰이는 datepicker 컴포넌트입니다.
- chakra ui에서 `react-datepicker` or `dayzed` 사용을 권장하였기에 구현할 때 `react-datepicker`를 사용했습니다.

### 작업 상세 설명

- 한 가지 문제가 있는데, `w="100%"` 속성이 적용되지가 않습니다. `DatePicker`, `InputGroup`, `Input` 그 어디에 넣어봐도 적용이 안 됩니다.. 찾아보니, `DatePicker`를 감싸는 `div`로 커스텀을 할 수 있다기에 `Box`를 이용해서 줘보기도 하였으나 그것도 안됩니다.. 그래서 일단 `useRef`를 이용해서 억지로 끼워넣긴 했습니다.

### 리뷰 요구 사항

- `InputGroup`에서 `px` 단위로 직접 `width`를 지정해주면 또 그거대로 적용은 되나, 부모를 따라가도록 지정을 하면 적용이 되지 않는 현상이 발생합니다.. 2주 동안 앓던 부분인데 끝내 해결을 못해서 방법을 아신다면 알려주시면 감사하겠습니다🥲
- 또한, 지금 `useRef`로 해놓은 상태일 때 새로고침을 하면 크기가 잠깐 줄었다가 늘어나는 현상이 발생합니다. 이는 `useEffect` 없이 `useRef`만을 사용해도 똑같은 현상이 일어나고 아직 고칠 방법도 찾지 못했습니다..😭
- 달력 팝업 창에서 달력을 클릭하게 되면 자동으로 `Input`에 `focus`가 풀리게 됩니다. 한번에 날짜를 선택했을 때는 문제가 없지만, 다른 달로 넘기거나 달력의 다른 부분을 클릭하게 되면 `Input`에 `orange_dark` 색상이 풀려서 해제되는 것처럼 보입니다. 이를 해결하고자 `onChange`나 `onClose`를 이용해서 여러 시도도 해봤지만 다 실패했기에 피드백 주시면 정말 감사하겠습니다..🥲
```tsx
  const [selectedDate, setSelectedDate] = useState<Date | null>(null);

  const handleDateChange = (date: Date | null) => {
    setSelectedDate(date);
  };

  return (
    <Box w="400px" m={20}>
      <StyledDatePicker label="시작 날짜" selectedDate={selectedDate} onChange={handleDateChange} />
    </Box>
  );
```
- 리뷰 예상 시간 : 10분
### 미리 보기
- Input focus 해제되는 모습
![2024-04-11214843-ezgif com-video-to-gif-converter](https://github.com/BDD-CLUB/01-doo-re-front/assets/126975394/92801b45-7d63-4d35-8f9c-24713b853741)

- 새로고침 했을 때
![2024-04-11214925-ezgif com-video-to-gif-converter](https://github.com/BDD-CLUB/01-doo-re-front/assets/126975394/afd54b37-94be-44c5-82f8-65b1e8a9386c)

2024-05-09 04:03 UTC, jasper200207 requested changes
> 한 가지 문제가 있는데, w="100%" 속성이 적용되지가 않습니다. DatePicker, InputGroup, Input 그 어디에 넣어봐도 적용이 안 됩니다.. 찾아보니, DatePicker를 감싸는 div로 커스텀을 할 수 있다기에 Box를 이용해서 줘보기도 하였으나 그것도 안됩니다.. 그래서 일단 useRef를 이용해서 억지로 끼워넣긴 했습니다.

이 부분 살펴봤는데 `react-datepicker` 구조가
- wrapper
  - inputcontainer
    - inputgroup
      - 그외...

와 같은 식인데 문제는 `wrapper` 부분에 `witdh:100%` 가 적용되어 있지 않았습니다. 그래서, 해결방법은 생각보다 간단한데 그냥 `wrapper` 에 `width:100%` 을 주면 됩니다. `DatePicker` 에 쓸수 있는 props 중에 `wrapperClassName` 있는데 말 그대로 `wrapper` 에 `classname` 을 주는 겁니다. 그래서, `wrapper` 에 적절한 `classname` 을 주고 `style.css` 에서 해당 `classname` 에 `witdh:100%` 을 주니 해결되었습니다. 밑에는 예시 코드 입니다! 참고로, 해당 방법 사용시 `InputGroup` 에 %단위 넓이를 주어도 부모에 맞춰지는 것을 확인했습니다! 부모를 따라간다는게 이 의미라면 해결될듯 합니다.

- StyledDatePicker
```typescript
<DatePicker
        selected={selectedDate}
        onChange={onChange}
        wrapperClassName="styled_date_picker"
        customInput={
          <InputGroup w="100%">
```
- style.css
```css
.styled_date_picker {
  width: 100%;
}
```

> InputGroup에서 px 단위로 직접 width를 지정해주면 또 그거대로 적용은 되나, 부모를 따라가도록 지정을 하면 적용이 되지 않는 현상이 발생합니다.. 2주 동안 앓던 부분인데 끝내 해결을 못해서 방법을 아신다면 알려주시면 감사하겠습니다🥲
또한, 지금 useRef로 해놓은 상태일 때 새로고침을 하면 크기가 잠깐 줄었다가 늘어나는 현상이 발생합니다. 이는 useEffect 없이 useRef만을 사용해도 똑같은 현상이 일어나고 아직 고칠 방법도 찾지 못했습니다..😭

제가 알기로는 렌더링 순서 문제인듯 합니다. `useRef` 를 사용하는 부분에서 알수 있듯이 `ref` 를 정해주는 건 `return` 즉 렌더링중에 일어납니다. 즉, 순서가 `Box 렌더링 -> ref 지정 -> Box 사이즈 변경 -> Box 다시 렌더링` 이 되는거죠. 이때, 먼저 렌더링된 `Box` 는 `width` 가 달라 그런 현상이 이러나는 걸로 추측됩니다... 위의 해결 방법을 사용하면 `ref` 를 사용할 필요가 없어서 해당 문제는 해결될 듯 합니다.

> 달력 팝업 창에서 달력을 클릭하게 되면 자동으로 Input에 focus가 풀리게 됩니다. 한번에 날짜를 선택했을 때는 문제가 없지만, 다른 달로 넘기거나 달력의 다른 부분을 클릭하게 되면 Input에 orange_dark 색상이 풀려서 해제되는 것처럼 보입니다. 이를 해결하고자 onChange나 onClose를 이용해서 여러 시도도 해봤지만 다 실패했기에 피드백 주시면 정말 감사하겠습니다..🥲

해당 방법은 chakra와 css로 해결가능합니다. css 속성중에는 `focus` 외에 `focuswithin` 이 있는데 해당 속성은 자신을 포함한 자신의 자식까지도 `focus` 효과를 줍니다. chakra에는 해당 속성을 쉽게 쓰기 위해 `_group_focuswithin` 이 있는데 해당 props 가 `focuswithin` 을 활용하여 `group` 안에 있는 모든 요소가 `focus` 를 함께 받도록 할 수 있습니다. 이 `_group_focuswithin` 이 그냥 `_focuswithin` 보다 좋은 점은 그룹으로 묶여만 있다면 자식이 부모 형제 상관없이 `role="focus"` 인 요소를 기준으로 `focus` 를 인식합니다. 즉, 최상단인 `Box` 에 `role="group"` 을 주고 기존 input 태마에서 `_focus` 를 `_group_focuswithin` 으로 바꾸면 문제가 해결됩니다! 아래는 예시 코드 입니다.

- StyledDatePicker
```typescript
return (
    <Box w="100%" role="group">
      <DatePicker
        selected={selectedDate}
        onChange={onChange}
```
- input.ts
```typescript
default: definePartsStyle({
      field: {
        bg: 'orange_light',
        color: 'white',
        rounded: '2xl',
        _groupFocusWithin: {
          borderColor: 'orange',
          bg: 'orange',
        },
      },
```

모두 종합하여 만들어진 예시 코드 입니다.
- style.css
```css
.scroll::-webkit-scrollbar {
  width: 30px;
}

.scroll::-webkit-scrollbar-thumb {
  background-color: #f68564;
  border-radius: 48px;
  border: 12px solid #ffffff;
}

.scroll_hide::-webkit-scrollbar {
  width: 0px;
}

.styled_date_picker {
  width: 100%;
}
```

- StyledDatePicker/index.tsx
```typescript
import { Input, InputGroup, Icon, InputRightElement, Box } from '@chakra-ui/react';
import React from 'react';
import DatePicker from 'react-datepicker';
import { BiCalendar } from 'react-icons/bi';
import 'react-datepicker/dist/react-datepicker.css';

import { StyledDatePickerProps } from './types';

const StyledDatePicker: React.FC<StyledDatePickerProps> = ({ label, selectedDate, onChange }) => {
  return (
    <Box w="100%" role="group">
      <DatePicker
        selected={selectedDate}
        onChange={onChange}
        wrapperClassName="styled_date_picker"
        customInput={
          <InputGroup w="100%">
            <Input
              textStyle="bold_xl"
              _hover={{ cursor: 'pointer' }}
              _placeholder={{ color: 'white' }}
              placeholder={label}
              readOnly
              value={selectedDate ? selectedDate.toLocaleDateString() : ''}
            />
            <InputRightElement _hover={{ cursor: 'pointer' }}>
              <Icon as={BiCalendar} textStyle="bold_xl" mr="5" color="gray.50" />
            </InputRightElement>
          </InputGroup>
        }
      />
    </Box>
  );
};

export default StyledDatePicker;
```

- theme/components/input.ts
```typescript
import { inputAnatomy } from '@chakra-ui/anatomy';
import { createMultiStyleConfigHelpers } from '@chakra-ui/react';

const { definePartsStyle, defineMultiStyleConfig } = createMultiStyleConfigHelpers(inputAnatomy.keys);

const Input = defineMultiStyleConfig({
  defaultProps: {
    variant: 'default',
  },

  variants: {
    default: definePartsStyle({
      field: {
        bg: 'orange_light',
        color: 'white',
        rounded: '2xl',
        _groupFocusWithin: {
          borderColor: 'orange',
          bg: 'orange',
        },
      },
      element: {
        h: '40px',
        w: { base: '34px', lg: '36px', '2xl': '38px' },
      },
    }),
  },
});

export default Input;
```

2024-05-09 11:33 UTC, llddang reviewed
수고하셨습니다!

2024-05-09 11:33 UTC, llddang commented on src/components/StyledDatePicker/index.tsx
> +const StyledDatePicker: React.FC<StyledDatePickerProps> = ({ label, selectedDate, onChange }) => {
혹시 `React.FC`를 사용한 이유가 있을까요?

저희가 원래 사용하던 방식인 으로 하는 것이 더 통일성 있을 것 같습니다!
`const StyledDatePicker = ({ label, selectedDate, onChange }: StyledDatePickerProps)`

또한 요즘은 React.FC 사용을 지양하는 분위기라고 합니다.
궁금하시다면 [이 블로그](https://shape-coding.tistory.com/entry/TypeScript-ReactFC%EC%97%90-%EC%82%AC%EC%9A%A9%EC%97%90-%EB%8C%80%ED%95%B4-%EC%83%9D%EA%B0%81%ED%95%B4%EB%B3%B4%EA%B8%B0) 확인해주세요!

2024-05-10 15:25 UTC, yeonddori commented
공통 css가 아니면 css도 컴포넌트 폴더 안에 만들기로 했던 것 같은데, 맞는지 확인 부탁드립니다!

2024-05-16 10:11 UTC, llddang approved these changes
수고하셨습니다!

2024-05-16 10:48 UTC, jasper200207 approved these changes
👍

2024-05-16 11:43 UTC, merged