Feature/#7 학습카드 구현
BDD-CLUB/01-doo-re-front pull request #24
Opened 2024-02-04 09:48 UTC by mun-kyeong

### 관련 이슈

- #7 

### 작업 요약

- 학습카드 컴포넌트 제작입니닷

### 작업 상세 설명

- 학습카드 컴포넌트 제작입니다! app < page.tsx에 아래 코드 집어넣으면 확인가능합니다
- 우선 백엔드에서 받아오는 api를 확인할 수 없어서 임의로 지정해둔 상황입니다! 
api 확인되면 수정해서 다시 올리겟슴다
```javascript

'use client';

import StudyCard from '@/components/StudyCard';
import { Link } from '@chakra-ui/next-js';
import { Box } from '@chakra-ui/react';
import { studyCardData } from '@/mocks/studycard'; // Replace 'path-to-your-mock-file' with the actual path to your mock file

const Page = () => {
  return (
    <Box p="20">
      <StudyCard
        title={studyCardData.title}
        content={studyCardData.content}
        date={studyCardData.date}
        bookmark={studyCardData.bookmark}
      />
    </Box>
  );
};

export default Page;

```

### 리뷰 요구 사항

- 폴더구조 맞는지 확인 부탁드립니다!
- hover했을때 카드를 선택했다는 느낌을 주고싶어서 hover 시에 배경화면 gray.100 색이 뜨도록 했는데 괜찮을지! 도 궁금함다
  - transition 조금 넣어서 자연스럽게 선택되는 느낌을 줬습니당 :)
-  이 외에 수정 필요한 부분 있다면 알려주세요!

### 미리 보기

<img width="218" alt="image" src="https://github.com/BDD-CLUB/01-doo-re-front/assets/96461334/7d17fa9b-356b-43b1-910d-f63cc3a278ed">
<img width="221" alt="image" src="https://github.com/BDD-CLUB/01-doo-re-front/assets/96461334/d5bd4c55-f9be-4b75-bb5b-0245dd3b8136">

2024-02-14 12:16 UTC, jasper200207 requested changes

2024-02-14 12:16 UTC, jasper200207 commented on src/types.ts
> +}
이 파일 위치 `src/components/StudyAssetCard/types.ts` 가 맞는듯 합니다.

2024-02-14 12:17 UTC, mun-kyeong commented on src/types.ts
> +}
넵 수정해두겟습니닷

2024-02-14 12:30 UTC, jasper200207 approved these changes
👍

2024-02-14 12:40 UTC, pipisebastian commented on src/components/StudyAssetCard/index.tsx
> +        <Text color="gray.400" fontSize="xs">
피그마에선 gray200으로 되어있는 것 같습니다!

2024-02-14 12:40 UTC, pipisebastian commented on src/components/StudyAssetCard/index.tsx
> +        alt="Chakra UI"
alt에 학습카드! 를 더 표현하는건 어떨까용?

2024-02-14 12:40 UTC, pipisebastian commented on src/components/StudyAssetCard/index.tsx
> +          <Button w="fit-content" minW="2" px="0" variant="ghost">
Button을 커스텀하는거말고 iconButton 을 쓰는건 어떨까용?

2024-02-15 08:35 UTC, yeonddori requested changes

2024-02-15 08:35 UTC, yeonddori commented on src/mocks/study.jsx
> +export { studyAssetCardData };
Typescript의 장점을 살리고자 파일 확장자를 ts로 바꾸고, 코드를 이렇게 짜보는 것은 어떨까요?
비록 임의의 데이터일 뿐이지만, 코드를 짜면서 데이터 실수가 발생하더라도 금방 알 수 있기에 조금 더 타입 안정성을 높이고 가독성을 향상시킬 수 있을 것 같습니다 :)
```ts
import { StudyAssetCardProps } from '@/components/StudyAssetCard/types';

const studyAssetCardData: StudyAssetCardProps = {
  title: '자료이름1',
  content: '이번 포스팅은 [스터디 목적]에 관한것입니다. 먼저 [목차]는 이렇습니다.',
  date: '2024/01/01',
  bookmark: 1208,
};

export default studyAssetCardData;
```

Page에서 import는 이렇게 하면 됩니다!
`import studyAssetCardData from '@/mocks/study';`

2024-02-16 01:35 UTC, mun-kyeong commented on src/components/StudyAssetCard/index.tsx
> +        <Text color="gray.400" fontSize="xs">
헉 그렇네요 수정해두겠습니다!!

2024-02-16 01:35 UTC, mun-kyeong commented on src/components/StudyAssetCard/index.tsx
> +        alt="Chakra UI"
앗 이런 디테일 생각하지 못했군요,,, ㅎㅎ 반영해두겟습니다~~!

2024-02-16 01:36 UTC, mun-kyeong commented on src/components/StudyAssetCard/index.tsx
> +          <Button w="fit-content" minW="2" px="0" variant="ghost">
넵 좋습니다!! 수정해두겟습니다

2024-02-16 01:37 UTC, mun-kyeong commented on src/mocks/study.jsx
> +export { studyAssetCardData };
헉 자연스러 jsx를 써버린것 같네요 ... 큰일날뻔 햇군ㄷ요,,,, 타입 지정해두는것도 너무 좋습니다!! 수정해두겠습니다 :)

2024-02-18 05:06 UTC, llddang approved these changes
수고하셨습니다! 도리님이 말하신 것만 수정하시면 될 듯 합니당!

2024-02-21 13:15 UTC, mun-kyeong commented
하나 이슈가 있는데, `<Grid>, <SimpleGrid>` 이거 두개를 쓰다보니 `overflow:hidden` 이거 속성이 안먹히더라구요,,,
그래서 화면 작아서 컴포넌트 수가 4개 -> 3개로 줄어들때 wrap 되던데 nowrap 적용해도 `<Grid>` 자체의 속성인건지 계속 남겨집니닷,,
계속 수정해보다가 우선 다른 컴포넌트 구현도 남아있어서 우선 4개 기준으로만 가져오는걸로 하고 반응형은 세미나 후에 다시 구현해봐도 괜찮을까요...!

- 찾아보니까 `overflow:hidden` 이게 flex 속성이 들어가면 적용이 안되는 것 같은데 `<Grid> <SimpleGrid>` 얘네가 flex 계열이라 그런게 아닌가.. 싶긴 합니다..!
  - 그래서 일단 생각해둔 방식은 `useEffect()` 써서 화면 크기에 따라 ` studyAssetCardData.map()` 할때부터 데이터 셋 양을 결정하던지, 아니면 `<StudyAssetCard>` 자체에 `display:none` 속성을 줄 수 있는 porps를 따로 준다던가,, 하는 방식을 생각해보긴 했는데 혹시 더 좋은 방식 있으면 추천부탁드립니답.. 
[스택오버플로우, 챠크라 "overflow:hidden" 적용 안되는 현상](https://stackoverflow.com/questions/66523133/why-does-react-chakra-ui-overflow-not-work)

2024-02-21 14:40 UTC, yeonddori approved these changes
1시간 동안 코드를 이리저리 바꿔보며 다양한 시도를 했지만 모두 실패하고 끝내 저도 생각나는 건 useEffect를 사용하는 것밖에 없네요..ㅎㅎ 세미나 전까지 반응형, api 연결은 제외하기로 했으니 후에 따로 이슈 파서 하는 게 좋을 것 같아요! 수고하셨습니다👍

2024-02-21 14:46 UTC, mun-kyeong commented
ㅋㅋㅋ쿠ㅜㅠ 나중에 고생 꽤나 하겟군요,, 감사합니다!!

2024-02-21 14:46 UTC, merged