Feature/#8 스터디카드 구현
BDD-CLUB/01-doo-re-front pull request #25
Opened 2024-02-04 12:37 UTC by mun-kyeong

### 관련 이슈

- #8 

### 작업 요약

- 스터디 카드 컴포넌트 구현입니다

### 작업 상세 설명

- 아직은 `crop id`가 어떻게 쓰일지 모르겠어서 우선 <Image> id로 적어두었습니다! 
(사실 api 아직 다 안받은것 같긴 합니다,, percent에 대한 정보를 안념겨줘서 api 고정되면 고때 제대로 수정할께요!)
- 학습자료랑 마찬가지로 hover 되었을 때 background transition 효과 있습니다!
- `page.jsx`에 아래 코드 집어넣으면 확인할 수 있습니다!
```javascript
'use client';

import { Box } from '@chakra-ui/react';
import StudyCard from '@/components/StudyCard';
import { studyCardData } from '@/mocks/study';

const Page = () => {
  return (
    <Box m="20">
      <StudyCard
        name={studyCardData.name}
        description={studyCardData.description}
        startDate={studyCardData.startDate}
        endDate={studyCardData.endDate}
        cropId={studyCardData.cropId}
        percent={studyCardData.percent}
      />
    </Box>
  );
};

export default Page;

```

### 리뷰 요구 사항

- props가 좀 많아졌군요 ㅋㅋㅋㅋ 좋은 피드백 부탁드림다ㅏㅏ (냉정하게 해주셔요 px 1단위라도 괜찮슴니다)

### 미리 보기
<img width="235" alt="image" src="https://github.com/BDD-CLUB/01-doo-re-front/assets/96461334/e08624c1-4463-4a32-9605-a34fcdfb0f2a">
<img width="240" alt="image" src="https://github.com/BDD-CLUB/01-doo-re-front/assets/96461334/3e5380f7-f6f2-45d0-9276-0e29594abb4a">

2024-02-09 07:58 UTC, llddang commented
음... 프로젝트에 prettier가 적용되지 않은 것 같습니다. `src/components/StudyCard/index.tsx` 파일에 perttier와 관련된 워닝과 에러가 떠서 저장한번해보니 import 순서부터, components props 순서도 변경되었습니다.

2024-02-09 08:11 UTC, llddang requested changes

2024-02-09 08:11 UTC, llddang commented on src/components/StudyCard/index.tsx
> +          <Image src="\png\circle.png" alt="crops" w="16" mx="auto" py="4" id="cropId" />
현재 `cropId` props를 컴포넌트 단위에서 입력받고 사용하고 있지않습니다.
생각해보았을때, 이부분에서 사용하실 것 같은데요.
id 에 cropId를 넣어주고 싶으시다면 `id={cropId.toString()}` 이런 식으로 사용해주시면 될 것 같습니다.

2024-02-14 03:54 UTC, pipisebastian commented on src/components/StudyCard/index.tsx
> +const StudyCard = ({ name, description, startDate, endDate, cropId, percent }: studyCardProps) => {
`{ name, description, startDate, endDate, cropId, percent }: studyCardProps` 보다는 
`studyCardProps : studyCardProps`로 하고, `studyCardProps.name` 로 사용하는 방법은 어떨까요? 이 부분도 다같이 정해야할 것 같군요..! 
그리고 interface는 대문자로 시작하는걸로 알고있습니다! studyCardProps -> StudyCardProps

2024-02-14 12:00 UTC, mun-kyeong commented on src/components/StudyCard/index.tsx
> +          <Image src="\png\circle.png" alt="crops" w="16" mx="auto" py="4" id="cropId" />
넵!! 좋습니다. import 순서도 같이 적용해서 다시 pr 올리도록 하겠습니다 :)

2024-02-14 12:28 UTC, jasper200207 approved these changes
👍

2024-02-14 12:31 UTC, pipisebastian approved these changes
👍

2024-02-15 08:41 UTC, yeonddori requested changes

2024-02-15 08:41 UTC, yeonddori commented on src/mocks/study.tsx
여기도 파일 확장자 통일하면 좋을 것 같아요!

2024-02-16 01:37 UTC, mun-kyeong commented on src/mocks/study.tsx
넵!! 감사합니다 :)

2024-02-18 05:08 UTC, llddang approved these changes
수고하셨습니당!! 도리님이 말하신 것만 수정하시면 될것 같습니다!

2024-02-18 08:36 UTC, pipisebastian commented
스터디 카드 디자인이 조금 바뀐 것 같습니다..!

2024-02-19 07:35 UTC, mun-kyeong commented
넵 ㅜㅜ 그리고 px 크기도 다시 조절을 해야할 것 같아서 수정한 후에 pr 다시 올리겠습니다..!

2024-02-21 14:17 UTC, mun-kyeong commented
학습카드와 동일한 이슈 있습니다! (카드 wrap 되는거...)

2024-02-21 14:44 UTC, yeonddori approved these changes

2024-02-21 14:44 UTC, yeonddori commented on .vscode/settings.json
> +    "compounds": []
수고하셨습니다👍
혹시 이건 무슨 세팅인지 알 수 있을까요?

2024-02-21 14:48 UTC, mun-kyeong commented on .vscode/settings.json
> +    "compounds": []
아 그거 아마 npm run build 하면서 생겨난 친구들일텐데 얘네를 삭제할지, 아니면 어차피 빌드하면서 생성될 코드면 냅둘지 얘기가 오가다가 결론이 안난것 같네요,,!
우선 머지는 미루고 내일 얘기 꺼내보는게 좋을 것 같습니당

2024-02-22 10:23 UTC, merged