Feature/#280 스터디 목록 조회 api 연결
BDD-CLUB/01-doo-re-front pull request #281
Opened 2024-07-10 19:20 UTC by yeonddori

### 관련 이슈

- close #280 

### 작업 요약

- 스터디 목록 조회 api 연결했습니다.

### 리뷰 요구 사항

- [Feature/#249 스터디 crud api 연결](https://github.com/BDD-CLUB/01-doo-re-front/pull/279) 선행 리뷰 부탁드립니다!! 해당 pr을 기반으로 코드를 짰습니다.
- 타입을 정확히 어떻게 지정하자고 했는지 가물가물해서.. 맞는지 확인 부탁드립니다!
- 리뷰 예상 시간: 5분

### 미리 보기

![image](https://github.com/BDD-CLUB/01-doo-re-front/assets/126975394/629cd950-752b-410e-823c-8da695b3ce0e)

2024-07-11 06:21 UTC, jasper200207 approved these changes
👍

2024-07-11 06:22 UTC, jasper200207 requested changes
./src/app/team/[teamId]/study/[studyId]/page.tsx:33:36
Type error: Property 'name' does not exist on type 'StudyCardProps'.

build 오류 났습니다...

2024-07-11 14:43 UTC, jasper200207 approved these changes
👍

2024-07-15 00:46 UTC, mun-kyeong approved these changes
수고하셨습니다!

2024-07-15 05:31 UTC, llddang approved these changes
수고하셨습니다!

2024-07-15 16:40 UTC, merged