Feature/#33 스터디페이지 참여인원 구현
BDD-CLUB/01-doo-re-front pull request #34
Opened 2024-02-15 08:02 UTC by yeonddori

### 관련 이슈

- #33 

### 작업 요약
- 스터디장 외 나머지 참여인원 가나다순으로 정렬
- 스크롤바 구현

### 작업 상세 설명
Page는 다음과 같이 하였습니다.
```tsx
'use client';

import { Box } from '@chakra-ui/react';

import participantData from '@/mocks/participant';
import Participant from '@/theme/containers/study/Participant';

const Page = () => {
  return (
    <Box m="8">
      <Participant participantInfos={participantData} />
    </Box>
  );
};

export default Page;
```

### 리뷰 요구 사항
- types 파일 위치가 긴가민가해서 맞는지 확인 부탁드립니다.
- width와 height는 %보다는 vw, vh가 나을 것 같아 수정해보았는데 의견 부탁드립니다!
그때 100으로 해두자고 하였던 것 같은데, 100으로 맞춰놓기엔 화면이 너무 커서 임의로 30으로 해두었습니다.

> vw와 vh는 열려있는 화면 전체의 상대길이이기 때문에 스크롤바를 포함한 길이를 기준으로 계산되는 반면, %는 창의 중심이 아닌, %를 쓰고 있는 요소의 부모 요소의 길이를 기준으로 계산되어 반환됩니다. 또한 그냥 전체 화면의 %를 쓴다고 하더라도 스크롤바를 포함하지 않은 현재 화면 길이를 기준으로 계산된다는 차이점이 있습니다.
물론 컴포넌트를 많이 파고들 것 같진 않지만, 밑의 컴포넌트로 파고들수록 원하는 결과 값을 얻기 힘들어지지 않을까 생각이 듭니다!

- 리뷰 예상 시간 : 5분

### 미리 보기
![스크린샷 2024-02-15 144833](https://github.com/BDD-CLUB/01-doo-re-front/assets/126975394/96514c87-6d5b-4459-9028-8435e86a7648) ![스크린샷 2024-02-15 144850](https://github.com/BDD-CLUB/01-doo-re-front/assets/126975394/796057b1-38b2-457e-bc0e-ea989baca1d9)
![_2024_02_15_14_51_51_423-ezgif com-video-to-gif-converter](https://github.com/BDD-CLUB/01-doo-re-front/assets/126975394/3a2ffb5a-906b-4222-b7db-9c042016ab55)

2024-02-15 10:59 UTC, llddang commented
지금 `/src/theme/containers/ `밑에  폴더를 생성하셨는데요, 수정해주셔야 할 것 같습니다.
theme 폴더는 Chakra UI component 자체를 커스텀하거나, 테마를 설정할 때 사용하는 폴더입니다!
@yeonddori 님이 작업하신 내용은 저희가 만든 특정 페이지에서 사용되는 component로 볼 수 있어 /src/ 폴더 바로 밑에 containers 폴더를 만들어서 작업해주시면 될 것 같습니다!
`/src/theme/containers/study/Participant` -> `/src/containers/study/Participant`

2024-02-15 11:08 UTC, yeonddori commented
@llddang 헉 저는 src 밑에 만든 줄 알았는데 theme 밑에 만들었군요 ㅋㅋㅋ ㅜㅜ.. 수정해서 올리겠습니다!!

2024-02-15 11:14 UTC, llddang requested changes

2024-02-15 11:14 UTC, llddang commented on src/theme/containers/study/Participant/types.ts
> +}
이 부분은 components의 props 관련이 아닌 api 관련이라서 `/src/types.ts`파일에 저장해주시면 좋을 것 같습니다.

2024-02-15 11:14 UTC, llddang commented on src/theme/containers/study/Participant/style.css
> +}
`-webkit-`이라는 접두어를 붙여서 작성해주셨는데요, 이렇게 되면 크롬 사파리등 특정 브라우저에서만 적용됩니다.. 사실 전체 적용할 수 있는 방법이 없어서 접두어를 붙여서 사용하는 것으로 알고 있긴 한데요. 저희가 아직 어떤 브라우저에서만 지원을 해줄지 정하지 않아서 수정이 시급해보이지는 않습니다. 나중에 어떤 브라우저를 지원할지 정하고 생각해봐야할 것 같습니다!
접두사 개념이 궁금하시다면 [이 블로그](https://jake-seo-dev.tistory.com/573) 추천합니다!

2024-02-15 12:03 UTC, yeonddori commented on src/theme/containers/study/Participant/types.ts
> +}
`/src/types.ts`는 공통 컴포넌트 관련된 것만 들어가는 걸로 이해하고 있었는데 api 관련도 들어가는군요! 커밋이 살짝 꼬였지만 수정 반영했습니다!

2024-02-15 12:05 UTC, pipisebastian commented on src/containers/study/Participant/index.tsx
> +              <Avatar shadow="md" size="xs" src={data.profileImg} />
이제 size="sm"으로 하면 shadow, size가 디자인대로 적용될겁니당!

2024-02-15 12:06 UTC, pipisebastian commented on src/containers/study/Participant/index.tsx
> +                <Text ml="2" color={color} fontSize="sm" fontWeight="bold">
디자인에서는 fontSize가 md인것 같아요!

2024-02-15 12:10 UTC, pipisebastian commented on src/containers/study/Participant/index.tsx
> +      <Box>
Box컴포넌트가 꼭 필요한건지 궁금합니다! Flex, Box를 같이 쓰는것말고도 Card로 써도 좋을 것 같아요!
커리큘럼, 피드, 참여인원 컴포넌트 3개가 모두 같은 디자인인 것 같은데, Card하나로 shadow, rounded만 건들면, 좀 더 쉬워지지 않을까해요!  
+ 그리고 rounded의 경우엔 디자인에 따로 속성이 안보이는 것 같은데, 2xl가 맞는지 확인한번 해보시면 좋을 것 같습니당!

2024-02-15 12:12 UTC, yeonddori commented on src/theme/containers/study/Participant/style.css
> +}
저도 스크롤바 관련해서 많이 찾아봤었는데 모든 브라우저에 적용하기도 힘들고, 그렇다고 그냥 두기엔 비슷하게라도 만들고 싶어서 최후의 결단으로 내린 방법이 결국 이거였습니다..🥲 나름 개발자들이니까 대다수 크롬을 사용하지 않을까..? 라는 생각으로 하긴 했습니다. 그치만 땅님 말씀처럼 나중에 정하고 나서 생각해봐야 할 것 같네요! 블로그 추천도 감사합니다😊

2024-02-15 12:17 UTC, pipisebastian commented on src/containers/study/Participant/index.tsx
> +  });
정렬 굿입니당!👍 그렇지만 백엔드에서 정렬해서 달라!!!하는 것도 좋을 것 같아요!

2024-02-15 12:20 UTC, pipisebastian commented on src/containers/study/Participant/style.css
> +  background-color: #f68564;
orange 색이군요! 음... constant 파일을 빼서 컬러 헥사값을 따로 저장해두고, 필요한데서 가져오는게 좋을 것 같아요!

헥사값을 여러군데서 가져오면 이게 무슨 색인지 보기 어려우니까용! 저번에 하기로 했었는데 제가 까먹었습니다..🥲  
혹시 이거 내일 저녁쯤에 해도 괜찮을까요?

2024-02-15 12:28 UTC, jasper200207 approved these changes
👍

2024-02-15 12:32 UTC, yeonddori commented on src/containers/study/Participant/index.tsx
> +              <Avatar shadow="md" size="xs" src={data.profileImg} />
`<Avatar size="sm" src={data.profileImg} />` 이렇게 했는데 왜 저는 원래 sm 사이즈와 shadow도 없이 나오는 것일까요.. npm i도 했고 vscode 리로드도 했는데, 따로 import 없이 원래 되는 것 아닌가요? ㅜㅜ

2024-02-15 12:33 UTC, yeonddori commented on src/containers/study/Participant/index.tsx
> +                <Text ml="2" color={color} fontSize="sm" fontWeight="bold">
앗, 그러네요! 확인했습니다!

2024-02-15 12:41 UTC, yeonddori commented on src/containers/study/Participant/style.css
> +  background-color: #f68564;
안그래도 색상을 어쩌나 했었는데 css파일도 따로 하기로 했었군요..!
좋습니다! 반영 되는대로 저도 수정하겠습니다👍

2024-02-15 12:43 UTC, yeonddori commented on src/containers/study/Participant/index.tsx
> +  });
아!! 그러네요! 제가 다 해야한다고 생각이 들었어서 주섬주섬..
api 연결할 때 백엔드분이 해주신다면 바로 지워버려야겠습니다👍

2024-02-15 12:59 UTC, yeonddori commented on src/containers/study/Participant/index.tsx
> +      <Box>
처음 피드를 구현할 때 Box로 구현을 시작했어서 자연스럽게 참여인원도 Box로 시작하게 됐어요. 배치를 맞춘다고 이것저것 추가하고 빼기를 반복하다 보니 좀 더러워진 것 같긴 하네요! 피피님 말씀처럼 Card로도 쉽게 가능할 것 같아서 수정해서 올려볼게요! 그리고 radius 속성 Chakra 페이지 따로 작성해둔 곳에서 2xl인 거 확인했습니다!

2024-02-16 00:35 UTC, pipisebastian commented on src/containers/study/Participant/index.tsx
> +              <Avatar shadow="md" size="xs" src={data.profileImg} />
허거걱 죄송합니다.. https://github.com/BDD-CLUB/01-doo-re-front/pull/42/files#diff-57b2e05901183e501b094c0102651a7631f1262a0dc1b84d61db844ec0423031 이걸 적용시켜야하는데, 제가 사이드바 브랜치에서 적용시켰습니다..  이게 머지되야지 적용될겁니다 ㅠㅠㅠ 저때문에 삽질하셨겠군요.. 죄송합니다ㅜ🙇‍♂️

2024-02-16 00:41 UTC, pipisebastian commented on src/containers/study/Participant/index.tsx
> +  });
줏섬줏섬...! 먼저 백엔드 담당자님한테 이거 정렬 어케되어있나요? 물어보고 해달라!! 하는것도 좋을 것 같아용!

2024-02-18 05:24 UTC, llddang approved these changes
피피님이 말하신 것이 머지되면 반영해서 수정해주시는 것만 해주시면 될듯합니다!
수고하셨습니다!!

2024-02-19 00:39 UTC, pipisebastian commented on src/containers/study/Participant/style.css
> +  background-color: #f68564;
앗 혹시 괜찮다면 모든 페이지에 해당 css파일이 적용되도록 해주실 수 있을까요? 커리큘럼, 피드, 참여인원 모두 해당 스크롤바인것 같아서요! 따로 이슈파셔서 작업하는게 좋아보입니당!

2024-02-19 01:07 UTC, pipisebastian commented on src/mocks/participant.ts
> +];
[노션 api](https://www.notion.so/API-b40f19b3cf9c4353a389a62186171873?p=4103224b249c4d7abbdb10ba23026189&pm=s)에서는 mocks data가 다 다릅니다,,,! 백엔드 db와 맞추기 위해
myPageUrl-> imageUrl, profileImg-> imageUrl등으로 변경해야할 것 같고, 스터디원인지, 스터디장인지 구분하는 status와 관련해서는 백엔드에서 아예 던져주고 있지 않습니다!

또한, api 문서에는 필요없는 데이터도 많은 것 같습니다. createdAt라던가, isDeleted라던가...
member 배열 하나만 던져줘도 괜찮지 않을까.. 합니다! 이 부분은 도리님이 개발하시면서, 필요없는 부분은 백엔드 담당자님인 팜님한테 필요없어요! 이거 내놔요! 하시면 될 것 같습니다!

제일 좋은거는 필요한 json객체를 하나 만드셔서, 이 형태로 보내주세요! 하는게 좋긴 합니다! (+ 왜 이게 없고, 이게 있는지에 대한 설명도요!)

2024-02-19 01:12 UTC, pipisebastian commented on src/mocks/participant.ts
> +];
그리고,  스터디원, 스터디장을 status 같은 값을 하나 더 줘서 판별하는게 나을지, 
아예 스터디장 불러오는 api를 만들어달라! 하는건 어떨까나요,,,! 뭐가 더 성능적으로 좋을지 모르겠네용,,

2024-02-19 01:13 UTC, pipisebastian commented on src/mocks/participant.ts
> +];
일단 api관련해서는 나중에 api 연결 이슈를 따로파서 작업해도 좋을 것 같습니다!
아직 api가 확정인것도 아니고, ui가 급하니까요,,!

2024-02-19 08:54 UTC, yeonddori commented on src/mocks/participant.ts
> +];
api 명세 db에서 스터디 참여인원 조회를 찾지 못해 아직 없는 것인 줄 알았는데, 스터디 db를 클릭해야 보이는 거였네요🥲 저도 이 브랜치에서보다는, 담당자분과 상의 후 api 연결 이슈를 따로 파서 작업하는것 좋은 것이 같아요! 알려주셔서 감사합니다!

2024-02-19 09:06 UTC, yeonddori commented on src/containers/study/Participant/style.css
> +  background-color: #f68564;
스크롤 두께를 비슷하게 하려다보니, 보더 길이를 생각보다 크게 잡아놓아서, 지금 바로 모든 파일에 적용시키기엔 작업해놓으신 커리큘럼의 배치(특히 체크박스)에 영향을 줄 수도 있을 것 같아요. 피드를 구현할 때 이 부분에 대해 스트레스를 받았던 적이 있어서요..🥲 커리큘럼까지 머지되고 난 후 그에 맞춰 따로 이슈 파서 적용시켜도 괜찮을까요?

2024-02-19 09:29 UTC, yeonddori commented on src/containers/study/Participant/style.css
> +  background-color: #f68564;
혹시 ts로 정의된 constant 파일을 css 파일에는 어떻게 적용 시키나요? 찾아봐도 잘 모르겠습니다 ㅜ

2024-02-21 01:02 UTC, pipisebastian commented on src/containers/study/Participant/style.css
> +  background-color: #f68564;
> 스크롤 두께를 비슷하게 하려다보니, 보더 길이를 생각보다 크게 잡아놓아서, 지금 바로 모든 파일에 적용시키기엔 작업해놓으신 커리큘럼의 배치(특히 체크박스)에 영향을 줄 수도 있을 것 같아요. 피드를 구현할 때 이 부분에 대해 스트레스를 받았던 적이 있어서요..🥲 커리큘럼까지 머지되고 난 후 그에 맞춰 따로 이슈 파서 적용시켜도 괜찮을까요?

넵!

2024-02-21 01:12 UTC, pipisebastian commented on src/containers/study/Participant/style.css
> +  background-color: #f68564;
> 혹시 ts로 정의된 constant 파일을 css 파일에는 어떻게 적용 시키나요? 찾아봐도 잘 모르겠습니다 ㅜ

헐룽.. 이게.. 안되네요,,! 음... 아예 color.css를 만들어서 import하는걸 해야하나 싶습니당..
일단은 머지하고 이것도 다음 회의때 어떻게할지 다같이 정해보는거 어떨까용,,!

2024-02-21 01:13 UTC, pipisebastian approved these changes
수고하셨습니당!! 👍

2024-02-21 07:43 UTC, merged